### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by drhouse** [JoshuaWise/javascript-ultimate#12]
Using Package Control, I got "Error loading syntax file Packages\JavaScript Ultimate\JSON.tmLanguage" and "Packages\JavaScript Ultimate\Javascript (DOM).tmLanguage". I tried restarting, disabling, uninstalling, reinstalling. I followed "Before uninstalling JavaScript Ultimate, be sure close all open JavaScript/JSON files...etc" Always gives same error on launch.

**Comment by JoshuaWise** [comment]
Which version of Sublime Text are you running?

**Comment by drhouse** [comment]
ST3 Build 3083

**Comment by drhouse** [comment]
Ok I fixed it. The difficulty was that all ***_.sublime_**_\* files and some other files were being marked with the js ultimate syntax, even though they're not literal .js/.json extension filetypes. If anyone else has this problem:
- you may want to take a screenshot of the open files in the sidebar to keep track of what was open
- open '\Local\Session.sublime_session' and search for the "syntax": lines containing 'Ultimate' 
- look at the associated 'file' name or buffer # a few lines above and close any files with that syntax
