### ISSUE TITLE
Template Strings

### ISSUE THREAD

**Issue by SirCxyrtyx** [JoshuaWise/javascript-ultimate#14]
I'm really liking this package, but the lack of support for template strings is holding me back from using them. Will you be updating this to properly highlight them? Template strings are [supported in Chrome, FF, Edge, and Safari.](http://kangax.github.io/compat-table/es6/#template_strings)

**Comment by JoshuaWise** [comment]
I plan to add total ES6 support all at once, as soon as Sublime Text releases their `.sublime-syntax` language format.

**Comment by rkgttr** [comment]
Hey Joshua,

Sublime Build 3103 implements the `.sublime-syntax` language, right?
When will you have a chance to update your awesome package?

Thanks.

**Comment by LionOps** [comment]
Ran into this. Would love to see a fix!

**Comment by JoshuaWise** [comment]
It's in progress! Stay tuned!

**Comment by kapooostin** [comment]
Any news on this issue?

**Comment by JoshuaWise** [comment]
Full ES6 Support is almost complete (it's a complete rewrite of the current JavaScript Ultimate). I estimate to have it released before the end of January

**Comment by JoshuaWise** [comment]
Full ES6 support has been released. Update your JavaScript Ultimate for template literal support.
