### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by MiguelDebruyne** [JoshuaWise/javascript-ultimate#16]
Hi there,

As I understand the default JavaScript.sublime-syntax.cache get's replaced with a custom one from this plugin. This is probably the problem that all my JS snippets don't work.

`<!-- Optional: Set a scope to limit where the snippet will trigger -->`
`<!-- <scope>source.JavaScript</scope> -->`

I tried to change it to `Javascript (DOM)` but that doesn't work; Even deleting these lines won't make it work. How can this be fixed?

**Comment by JoshuaWise** [comment]
Have you tried:
`<scope>source.js</scope>`

Also, are all your snippets stored in your `User` package folder?

**Comment by MiguelDebruyne** [comment]
Thank you for the fast reply.

I put my snippets in `User/snippets/*codelanguage*/` to at least have some structure within the user folder and my snippets as well. Moving them directly into the `Users` folder seemed to fix the problem. I didn't have to change the `scope`.

It's great that that the plugin works now, but wouldn't it be possible to be able to load the snippets wherever they are within the `User` folder?

**Comment by JoshuaWise** [comment]
I'm glad you got it working. JavaScript Ultimate handles snippets the same way the default JavaScript syntax does, so any difference in behavior is most likely a bug in Sublime Text itself.
