### ISSUE TITLE
SublimeLinter syntax mapping

### ISSUE THREAD

**Issue by jgowdyelastic** [JoshuaWise/javascript-ultimate#18]
After a recent change, it appears the syntax mapping for JavaScript (DOM) now needs to be:
```
"syntax_map": { 
    "javascript.dom": "javascript" 
}
```
README.md should probably be updated to reflect this

**Comment by JoshuaWise** [comment]
Thanks. Updated via 7e2c326716c6bc0b4dbfa5da777d31de587bf78d
