### ISSUE TITLE
default JavaScript package does not get disabled

### ISSUE THREAD

**Issue by spectacles** [JoshuaWise/javascript-ultimate#2]
After installing Ultimate JavaScript :+1: I now have two JavaScript Syntax definitions. The original and Ultimate. Both are activated and it is not possible to set Ultimate as default for all js Files. I can activate it though by clicking again on the (already indicated as active) Ultimate syntax. 

Please, what could be the problem?

**Comment by spectacles** [comment]
FYI: after reviewing the latest commits, I added "JavaScript" to the ignored_packages manually. Now everything is working!

**Comment by JoshuaWise** [comment]
Ideally, the default JavaScript package would be disabled upon installation, but this can only happen if the [Package Control events](https://packagecontrol.io/docs/events) work properly. Unfortunately, I couldn't get them to. I emailed Will Bond about the issue, and hopefully I'll get a response soon.

In the meantime, I pushed a hotfix that will simply disable the default JavaScript package every time the package is loaded. But if you uninstall JavaScript Ultimate, you'll have to manually re-enable the default JavaScript package (at least, for now).

If anybody still encounters the same problem as @spectacles, let me know here, and tell me which version of Sublime Text you're using.

**Comment by brandonpapworth** [comment]
@JoshuaWise Disabling the default JavaScript package causes Sublime Text 3 (at least as of build 3087) to fail loading many template languages (like MultiMarkdown). See [Dev Build 3088](https://www.sublimetext.com/forum/viewtopic.php?f=2&p=68751) . This might just be a regression in Sublime Text 3's ongoing development, but some forum members seem to indicate this may be an actual design-decision from hereon out.

**Comment by JoshuaWise** [comment]
I don't believe this is an issue anymore. If you have this problem with the newest version of JavaScript Ultimate, post here and I'll reopen the issue.
