### ISSUE TITLE
error comments in HTML with JavaScript

### ISSUE THREAD

**Issue by icepole-jon** [JoshuaWise/javascript-ultimate#22]
![](https://ws1.sinaimg.cn/large/5faa2d0bgy1fizhuvirpkj20so0lk0tg.jpg)

**Comment by JoshuaWise** [comment]
Update your package, it should be fixed now. Thanks for bringing this to my attention.

**Comment by icepole-jon** [comment]
:(
what i mean is that when you use shortcut key (Ctrl + / or Ctrl + shift + /) to add comments, it should be use
```javascript
//  one line comments
/*   block comments  */
```
for JavaScript NOT 
```html
<!-- -->
```
it is not about highlight color's mater...
when i disable this package and use default JavaScript package, it is works fine..
anyway thanks a lot and i think the original highlight is right...

**Comment by JoshuaWise** [comment]
Ahh okay, sorry I misunderstood.

I've released a new patch (3.11.2) that should fix that problem (ignore 3.11.1). Also I've restricted the html-style comments (`<!-- -->`) to only apply to the `JavaScript (DOM)` variant.
