### ISSUE TITLE
Default to javascript rather than javascript(DOM)

### ISSUE THREAD

**Issue by alanquigley** [JoshuaWise/javascript-ultimate#5]
It would be great to default to javascript rahter than javascript(DOM) as sublimeLinter-jshint doesn't recognise javascript(DOM).

**Comment by JoshuaWise** [comment]
Don't forget you can easily set the default syntax to JavaScript by going to "Open all with current extension as" in the syntax selection menu. In any case, I'll probably make native JavaScript the default when I release the Nodejs syntax.

**Comment by alanquigley** [comment]
I had forgot, or rather never noticed that setting before, Cheers.
