### ISSUE TITLE
Can I use it with Java​Script​Next - ES6 Syntax package?

### ISSUE THREAD

**Issue by AuthorProxy** [JoshuaWise/javascript-ultimate#7]

**Comment by JoshuaWise** [comment]
They can be installed side-by-side, but they do not work together. They're separate syntaxes that function independently. However, it's recommended that you only have one installed at a time, because otherwise other 3rd party plugins can be confused.

**Comment by agauniyal** [comment]
Java​Script​Next - ES6 Syntax package highlights much better for node related files. However it lacks some features from this package.

**Comment by JoshuaWise** [comment]
When Sublime Text releases their `.sublime-syntax` feature on a stable channel, I plan to rewrite this package. When that happens, I plan to add a `JavaScript (Node)` syntax, similar to how there's currently a `JavaScript (DOM)` syntax. Also, when ES6 is fully supported across major browsers (Chrome, FF, Edge), I'll update the package to support those syntaxes.
