### ISSUE TITLE
Problems with SublimeLinter

### ISSUE THREAD

**Issue by druellan** [JoshuaWise/javascript-ultimate#8]
Seems that this package is not compatible with SublimeLinter. Javascript Ultimate works, but SublimeLinter silently fails to show the linting information.

I believe the problem is related to the fact that SublimeLinter "hacks" the color Scheme, cloning and creating their own variant.

I have a test environment in case you need more information, but (again) seems that the problem is related to the way SublimeLinter works.

**Comment by JoshuaWise** [comment]
Does this solve the problem?
[Issue #6](https://github.com/JoshuaWise/javascript-ultimate/issues/6)

**Comment by druellan** [comment]
Hi Joshua.
Yes! That seems to work. Worth adding it to the readme, SublimeLinter is a very popular add-on.

**Comment by dogoku** [comment]
This should be mentioned in the README! (Made a PR with the change)

I spend half a day trying to figure out why my linting stopped working. Then I remembered I installed this package

**Comment by JoshuaWise** [comment]
merged #10
