### ISSUE TITLE
Doesn't highlight HTML files with 3087 beta

### ISSUE THREAD

**Issue by larionov** [JoshuaWise/javascript-ultimate#9]
After upgrading to Sublime Text 3087 shows following error message and stops highlighting HTML files at all.

> Error loading syntax file "Packages/HTML/HTML.tmLanguage": Unable to read Packages/JavaScript/JavaScript.sublime-syntax

**Comment by todokaizen** [comment]
Same error for me as well. I tried, as a workaround, removing javascript from the exclude statement in my user config, that works but the exclude statement is reinserted upon restarting. 
I also had to switch the language of my html files to "HTML(angular.js)" to prevent unwanted highlighting the plain "HTML" designation produced.

**Comment by JoshuaWise** [comment]
I'll look into this further this week.

**Comment by larionov** [comment]
Seems like they fixed it in 3092
